---
# tasks file for roles/eval2

    - name: apt-get update
      apt:
        update_cache: yes

    - name: Installing Mysql + Dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
        - mysql-server
        - mysql-client 
        - python3-mysqldb
        - libmysqlclient-dev

    - name: Start and Enable Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Mysql User
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_password }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create Database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
    
    - name: Enable Remote Login
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql

